[package]
name = "cas"
version = "0.1.0"
edition = "2024"

[lib]
name = "cas"
crate-type = ["cdylib", "rlib"]

[dependencies]
rug = "1.28"
num-bigint = "*"
pyo3 = { version = "0.26.0", features = ["num-bigint"] }

[dev-dependencies]